#!/bin/sh
# kb-manifest.sh — Generate knowledge-index.mdc from YAML frontmatter in knowledge files.
# Usage: sh tools/kb-manifest.sh

set -e

KB_DIR=".cursor/knowledge"
INDEX_FILE=".cursor/rules/knowledge-index.mdc"

if [ ! -d "$KB_DIR" ]; then
  echo "ERROR: $KB_DIR not found" >&2
  exit 1
fi

# Count atom files (exclude old monolithic files by checking for frontmatter)
atom_count=0

# Build the index content in a temp file
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

# Header
cat > "$tmpfile" << 'HEADER'
---
description: "Knowledge base index — trigger-keyword lookup for atomic knowledge files"
alwaysApply: true
---
# Knowledge Index

Lookup table for `.cursor/knowledge/` atoms. Use triggers to find the right file.

| File | Triggers |
|------|----------|
HEADER

# Process each .md file in knowledge/ that has YAML frontmatter with trigger:
for f in "$KB_DIR"/*.md; do
  [ -f "$f" ] || continue

  basename=$(basename "$f")

  # Check naming convention: must be lowercase with -- separator
  case "$basename" in
    [a-z]*--*.md) ;;
    *) continue ;;  # skip files not matching atom naming convention
  esac

  # Extract trigger field from YAML frontmatter
  triggers=""
  in_frontmatter=0
  while IFS= read -r line; do
    if [ "$in_frontmatter" -eq 0 ]; then
      if [ "$line" = "---" ]; then
        in_frontmatter=1
        continue
      else
        break
      fi
    fi
    if [ "$line" = "---" ]; then
      break
    fi
    case "$line" in
      trigger:*)
        triggers=$(echo "$line" | sed 's/^trigger:[[:space:]]*//')
        ;;
    esac
  done < "$f"

  if [ -z "$triggers" ]; then
    echo "WARN: $basename has no trigger: field" >&2
    triggers="TODO"
  fi

  printf "| \`%s\` | %s |\n" "$basename" "$triggers" >> "$tmpfile"
  atom_count=$((atom_count + 1))
done

echo "" >> "$tmpfile"
printf "_Auto-generated by \`make kb-manifest\`. %d atoms indexed._\n" "$atom_count" >> "$tmpfile"

cp "$tmpfile" "$INDEX_FILE"
echo "OK: $INDEX_FILE generated ($atom_count atoms)"
