#!/bin/sh
# kb-manifest.sh — Generate knowledge-index.mdc from knowledge atoms and ADRs.
# Usage: sh tools/kb-manifest.sh

set -e

KB_DIR=".cursor/knowledge"
ADR_DIR="docs/adr"
INDEX_FILE=".cursor/rules/knowledge-index.mdc"

if [ ! -d "$KB_DIR" ]; then
  echo "ERROR: $KB_DIR not found" >&2
  exit 1
fi

atom_count=0
adr_count=0

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

# Header
cat > "$tmpfile" << 'HEADER'
---
description: "Knowledge base index — trigger-keyword lookup for knowledge atoms and Design documents"
alwaysApply: true
---
# Knowledge Index

Lookup table for `.cursor/knowledge/` atoms and `docs/adr/` ADRs. Use triggers to find the right file.

## Knowledge Atoms

| File | Triggers |
|------|----------|
HEADER

# Process each .md file in knowledge/ that has YAML frontmatter with trigger:
for f in "$KB_DIR"/*.md; do
  [ -f "$f" ] || continue

  basename=$(basename "$f")

  # Check naming convention: must be lowercase with -- separator
  case "$basename" in
    [a-z]*--*.md) ;;
    *) continue ;;
  esac

  # Extract trigger field from YAML frontmatter
  triggers=""
  in_frontmatter=0
  while IFS= read -r line; do
    if [ "$in_frontmatter" -eq 0 ]; then
      if [ "$line" = "---" ]; then
        in_frontmatter=1
        continue
      else
        break
      fi
    fi
    if [ "$line" = "---" ]; then
      break
    fi
    case "$line" in
      trigger:*)
        triggers=$(echo "$line" | sed 's/^trigger:[[:space:]]*//')
        ;;
    esac
  done < "$f"

  if [ -z "$triggers" ]; then
    echo "WARN: $basename has no trigger: field" >&2
    triggers="TODO"
  fi

  printf "| \`%s\` | %s |\n" "$basename" "$triggers" >> "$tmpfile"
  atom_count=$((atom_count + 1))
done

# ADR section
if [ -d "$ADR_DIR" ]; then
  cat >> "$tmpfile" << 'ADR_HEADER'

## Design (ADRs)

| File | Triggers |
|------|----------|
ADR_HEADER

  for f in "$ADR_DIR"/[0-9]*.md; do
    [ -f "$f" ] || continue

    basename=$(basename "$f")

    # Extract title from first heading: "# ADR-NNNN: Title"
    title=""
    while IFS= read -r line; do
      case "$line" in
        "# ADR-"*)
          title=$(echo "$line" | sed 's/^# ADR-[0-9]*:[[:space:]]*//')
          break
          ;;
        "# "*)
          title=$(echo "$line" | sed 's/^#[[:space:]]*//')
          break
          ;;
      esac
    done < "$f"

    if [ -z "$title" ]; then
      echo "WARN: $basename has no recognizable title heading" >&2
      title="TODO"
    fi

    # Generate ADR number trigger (e.g., "ADR-0001")
    adr_num=$(echo "$basename" | sed 's/^\([0-9]*\)-.*/ADR-\1/')

    # Convert title to trigger keywords: lowercase, remove stop words
    keywords=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr '-' ' ' | \
      sed 's/[^a-z0-9 ]//g' | \
      tr ' ' '\n' | \
      grep -v -E '^(use|the|a|an|and|or|for|in|of|to|with|is|are|was|were|be|been|has|have|had|do|does|did|will|would|shall|should|may|might|can|could)$' | \
      grep -v -E '^.{0,2}$' | \
      tr '\n' ', ' | \
      sed 's/,$//' | sed 's/,/, /g')

    triggers="$adr_num, $keywords"

    printf "| \`%s\` | %s |\n" "$basename" "$triggers" >> "$tmpfile"
    adr_count=$((adr_count + 1))
  done
fi

echo "" >> "$tmpfile"
printf "_Auto-generated by \`make kb-manifest\`. %d atoms, %d ADRs indexed._\n" "$atom_count" "$adr_count" >> "$tmpfile"

cp "$tmpfile" "$INDEX_FILE"
echo "OK: $INDEX_FILE generated ($atom_count atoms, $adr_count ADRs)"
