#' Constraint S7 Classes
#'
#' S7 classes for inter-parameter technical constraints. Constraints define
#' what "can/cannot" be done and are mostly auto-generated by `scan_package()`
#' (ADR-0004, ADR-0008).
#'
#' @name constraints
#' @importFrom rlang %||%
NULL

# -- Constraint ---------------------------------------------------------------

.valid_constraint_sources <- c(
  "formals_default", "rd_description", "source_code", "expert"
)

.valid_constraint_types <- c(
  "forces", "requires", "valid_values", "incompatible", "conditional"
)

.valid_confidence_levels <- c("high", "medium", "low", "gap")

#' @title Constraint
#' @description A single inter-parameter technical constraint. The `type`
#' field determines which optional fields are semantically required.
#' @param id Unique identifier (character).
#' @param source Extraction source (character). One of `"formals_default"`,
#'   `"rd_description"`, `"source_code"`, `"expert"`.
#' @param type Constraint type (character). One of `"forces"`, `"requires"`,
#'   `"valid_values"`, `"incompatible"`, `"conditional"`.
#' @param param Target parameter name (character).
#' @param condition R expression for when this constraint fires (character).
#' @param forces Forced parameter values (named list).
#' @param requires Required parameter values (named list).
#' @param values Valid value list (character vector).
#' @param incompatible Incompatible value combinations (named list).
#' @param enabled_when Condition under which the parameter is effective
#'   (character).
#' @param message Human-readable message (character).
#' @param confirmed_by Layers that confirmed this constraint (character vector).
#' @param confidence Confidence grade (character). One of `"high"`, `"medium"`,
#'   `"low"`, `"gap"`.
#' @export
Constraint <- S7::new_class("Constraint",
  properties = list(
    id = S7::class_character,
    source = S7::class_character,
    type = S7::class_character,
    param = S7::new_property(S7::class_character, default = character(0)),
    condition = S7::new_property(S7::class_character, default = character(0)),
    forces = S7::new_property(S7::class_list, default = list()),
    requires = S7::new_property(S7::class_list, default = list()),
    values = S7::new_property(S7::class_character, default = character(0)),
    incompatible = S7::new_property(S7::class_list, default = list()),
    enabled_when = S7::new_property(S7::class_character, default = character(0)),
    message = S7::new_property(S7::class_character, default = character(0)),
    confirmed_by = S7::new_property(S7::class_character, default = character(0)),
    confidence = S7::new_property(S7::class_character, default = character(0))
  ),
  validator = function(self) {
    if (length(self@id) != 1L || nchar(self@id) == 0L) {
      return("`id` must be a non-empty single string")
    }
    if (length(self@source) != 1L || !self@source %in% .valid_constraint_sources) {
      return(sprintf(
        "`source` must be one of: %s",
        paste(dQuote(.valid_constraint_sources, FALSE), collapse = ", ")
      ))
    }
    if (length(self@type) != 1L || !self@type %in% .valid_constraint_types) {
      return(sprintf(
        "`type` must be one of: %s",
        paste(dQuote(.valid_constraint_types, FALSE), collapse = ", ")
      ))
    }
    type_err <- check_type_fields(self)
    if (!is.null(type_err)) {
      return(type_err)
    }
    has_confidence <- length(self@confidence) == 1L
    if (has_confidence && !self@confidence %in% .valid_confidence_levels) {
      return(sprintf(
        "`confidence` must be one of: %s",
        paste(dQuote(.valid_confidence_levels, FALSE), collapse = ", ")
      ))
    }
    for (cb in self@confirmed_by) {
      if (!cb %in% .valid_constraint_sources) {
        return(sprintf(
          "`confirmed_by` values must be valid source types (got \"%s\")", cb
        ))
      }
    }
    NULL
  }
)

#' @keywords internal
check_type_fields <- function(constraint) {
  tp <- constraint@type
  if (tp == "forces" && length(constraint@forces) == 0L) {
    return("Constraint of type \"forces\" must have a non-empty `forces` field")
  }
  if (tp == "requires" && length(constraint@requires) == 0L) {
    return("Constraint of type \"requires\" must have a non-empty `requires` field")
  }

  if (tp == "valid_values" && length(constraint@values) == 0L) {
    return(
      "Constraint of type \"valid_values\" must have a non-empty `values` field"
    )
  }
  if (tp == "incompatible" && length(constraint@incompatible) == 0L) {
    return(
      "Constraint of type \"incompatible\" must have a non-empty `incompatible` field"
    )
  }
  if (tp == "conditional" && length(constraint@enabled_when) == 0L) {
    return(
      "Constraint of type \"conditional\" must have a non-empty `enabled_when` field"
    )
  }
  NULL
}

# -- ConstraintSet ------------------------------------------------------------

#' @title ConstraintSet
#' @description A collection of constraints for a target package function.
#' Constraint IDs must be unique within the set.
#' @param package Target package name (character).
#' @param func Target function name (character).
#' @param constraints A list of [Constraint] objects.
#' @usage NULL
#' @export
ConstraintSet <- S7::new_class("ConstraintSet",
  properties = list(
    package = S7::class_character,
    func = S7::class_character,
    constraints = S7::class_list
  ),
  validator = function(self) {
    if (length(self@package) != 1L || nchar(self@package) == 0L) {
      return("`package` must be a non-empty single string")
    }
    if (length(self@func) != 1L || nchar(self@func) == 0L) {
      return("`func` must be a non-empty single string")
    }
    if (length(self@constraints) == 0L) {
      return("`constraints` must contain at least one Constraint")
    }
    ids <- character(length(self@constraints))
    for (i in seq_along(self@constraints)) {
      cst <- self@constraints[[i]]
      if (!S7::S7_inherits(cst, Constraint)) {
        return(sprintf("constraints[[%d]] must be a Constraint object", i))
      }
      ids[i] <- cst@id
    }
    if (anyDuplicated(ids)) {
      dup <- ids[duplicated(ids)][[1L]]
      return(sprintf("Duplicate constraint id: \"%s\"", dup))
    }
    NULL
  }
)

# -- YAML Reader --------------------------------------------------------------

#' Read Constraints from YAML
#'
#' Parses a constraints YAML file and returns a [ConstraintSet] object.
#'
#' @param path Path to the YAML file.
#' @return A [ConstraintSet] object.
#' @export
read_constraints <- function(path) {
  if (!file.exists(path)) {
    cli::cli_abort("File not found: {.path {path}}")
  }
  raw <- tryCatch(
    yaml::yaml.load_file(path),
    error = function(e) {
      cli::cli_abort("Failed to parse YAML: {conditionMessage(e)}", parent = e)
    }
  )
  parse_constraint_set(raw)
}

#' @keywords internal
parse_constraint_set <- function(raw) {
  pkg <- raw[["package"]]
  if (is.null(pkg)) {
    cli::cli_abort("{.field package} is required")
  }
  func <- raw[["function"]]
  if (is.null(func)) {
    cli::cli_abort("{.field function} is required")
  }
  constraints_raw <- raw[["constraints"]]
  if (is.null(constraints_raw) || length(constraints_raw) == 0L) {
    cli::cli_abort("{.field constraints} must be a non-empty list")
  }
  constraints <- lapply(constraints_raw, parse_constraint)

  ConstraintSet(
    package = pkg,
    func = func,
    constraints = constraints
  )
}

#' @keywords internal
parse_constraint <- function(raw) {
  id <- raw[["id"]]
  if (is.null(id)) {
    cli::cli_abort("Constraint is missing required field {.field id}")
  }
  src <- raw[["source"]]
  if (is.null(src)) {
    cli::cli_abort("Constraint {.val {id}} is missing required field {.field source}")
  }
  tp <- raw[["type"]]
  if (is.null(tp)) {
    cli::cli_abort("Constraint {.val {id}} is missing required field {.field type}")
  }

  forces <- as.list(raw[["forces"]] %||% list())
  requires <- as.list(raw[["requires"]] %||% list())
  incompatible <- as.list(raw[["incompatible"]] %||% list())

  values <- raw[["values"]]
  if (is.list(values)) values <- unlist(values)

  confirmed_by <- raw[["confirmed_by"]]
  if (is.list(confirmed_by)) confirmed_by <- unlist(confirmed_by)

  Constraint(
    id = id,
    source = src,
    type = tp,
    param = raw[["param"]] %||% character(0),
    condition = raw[["condition"]] %||% character(0),
    forces = forces,
    requires = requires,
    values = values %||% character(0),
    incompatible = incompatible,
    enabled_when = raw[["enabled_when"]] %||% character(0),
    message = raw[["message"]] %||% character(0),
    confirmed_by = confirmed_by %||% character(0),
    confidence = raw[["confidence"]] %||% character(0)
  )
}
